### ISSUE TITLE
Error on blog page: http://localhost:8080/blog

### ISSUE THREAD

**Issue by drupalninja** [octahedroid/drupal-decoupled#59]
Error in console:
<img width="1046" alt="Screenshot 2024-05-05 at 1 14 21 PM" src="https://github.com/octahedroid/drupal-decoupled/assets/1112449/89fa4253-1efc-422b-955a-9ff5f7c37977">

This is the error I got in the Drupal logs after a clean install, the other pages seem to work:
```
There were errors during a GraphQL execution. Operation details:
{
    "$operation": {
        "queryId": null,
        "query": "query route($path: String!) {\n  route(path: $path) {\n    __typename\n    ... on RouteInternal {\n      entity {\n        __typename\n        ... on NodePage {\n          id\n          title\n        }\n        ...NodePageFragment\n        ...NodeArticleFragment\n        ...TermTagsFragment\n      }\n    }\n  }\n}\nfragment NodePageFragment on NodePage {\n  __typename\n  id\n  title\n  showTitle\n  summary\n  image {\n    ...MediaImageFragment\n  }\n  metatag {\n    ...MetatagFragment\n  }\n  components {\n    ...ParagraphUnionFragment\n  }\n}\nfragment MediaImageFragment on MediaImage {\n  id\n  mediaImage {\n    ...ImageFragment\n  }\n}\nfragment ImageFragment on Image {\n  url\n  width\n  height\n  alt\n  title\n}\nfragment MetatagFragment on MetaTag {\n  __typename\n  ... on MetaTagLink {\n    attributes {\n      rel\n      href\n    }\n  }\n  ... on MetaTagValue {\n    attributes {\n      name\n      content\n    }\n  }\n  ... on MetaTagProperty {\n    attributes {\n      property\n      content\n    }\n  }\n}\nfragment ParagraphUnionFragment on ParagraphUnion {\n  ... on ParagraphInterface {\n    __typename\n    id\n  }\n  ...ParagraphCodeBlockFragment\n  ...ParagraphHeroCtaFragment\n  ...ParagraphTextFragment\n  ...ParagraphImageFragment\n  ...ParagraphHeroTextFragment\n  ...ParagraphStaticComponentFragment\n  ...ParagraphViewReference\n}\nfragment ParagraphCodeBlockFragment on ParagraphCodeBlock {\n  __typename\n  id\n  titleOptional\n  code\n  language\n  showLineNumbers\n}\nfragment ParagraphHeroCtaFragment on ParagraphHeroCta {\n  __typename\n  id\n  title\n  text\n  intro\n  cta {\n    ...LinkFragment\n  }\n}\nfragment LinkFragment on Link {\n  url\n  title\n  internal\n}\nfragment ParagraphTextFragment on ParagraphText {\n  __typename\n  id\n  title\n  textRich {\n    ...TextFragment\n  }\n}\nfragment TextFragment on Text {\n  format\n  value\n  processed\n}\nfragment ParagraphImageFragment on ParagraphImage {\n  __typename\n  id\n  image {\n    ...MediaImageFragment\n  }\n}\nfragment ParagraphHeroTextFragment on ParagraphHeroText {\n  __typename\n  id\n  intro\n  title\n  text\n}\nfragment ParagraphStaticComponentFragment on ParagraphStaticComponent {\n  __typename\n  id\n  component\n}\nfragment ParagraphViewReference on ParagraphViewReference {\n  __typename\n  id\n  reference {\n    __typename\n    ... on ViewBlogTeaserResult {\n      id\n      view\n      display\n      results {\n        ... on NodeArticle {\n          __typename\n          id\n          title\n          summary\n          path\n          image {\n            ...MediaImageFragment\n          }\n          author {\n            ...UserFragment\n          }\n        }\n      }\n    }\n  }\n}\nfragment UserFragment on User {\n  id\n  name\n  picture {\n    ... on MediaImage {\n      ...MediaImageFragment\n    }\n  }\n}\nfragment NodeArticleFragment on NodeArticle {\n  __typename\n  id\n  title\n  summary\n  path\n  image {\n    ...MediaImageFragment\n  }\n  author {\n    ...UserFragment\n  }\n  metatag {\n    ...MetatagFragment\n  }\n  components {\n    ...ParagraphUnionFragment\n  }\n}\nfragment TermTagsFragment on TermTags {\n  __typename\n  id\n  name\n  description {\n    processed\n  }\n}",
        "operation": "route",
        "variables": {
            "path": "blog"
        },
        "extensions": null
    },
    "$result->data": {
        "route": {
            "__typename": "RouteInternal",
            "entity": {
                "__typename": "NodePage",
                "id": "91e36ae5-c844-474a-83fc-56308a080b83",
                "title": "Blog",
                "showTitle": true,
                "summary": "blog ",
                "image": {
                    "id": "4edf81b6-9975-47d3-9a8d-8f1b6817af39",
                    "mediaImage": {
                        "url": "http:\/\/drupal-graphql-example.ddev.site\/sites\/default\/files\/2024-04\/composabale-drop-logo.png",
                        "width": 807,
                        "height": 1052,
                        "alt": "Drupal Composable",
                        "title": null
                    }
                },
                "metatag": [
                    {
                        "__typename": "MetaTagValue",
                        "attributes": {
                            "name": "title",
                            "content": "Blog | Drupal GraphQL Demo"
                        }
                    },
                    {
                        "__typename": "MetaTagLink",
                        "attributes": {
                            "rel": "canonical",
                            "href": "http:\/\/drupal-graphql-example.ddev.site\/blog"
                        }
                    },
                    {
                        "__typename": "MetaTagLink",
                        "attributes": {
                            "rel": "image_src",
                            "href": "http:\/\/drupal-graphql-example.ddev.site\/sites\/default\/files\/2024-04\/composabale-drop-logo.png"
                        }
                    },
                    {
                        "__typename": "MetaTagProperty",
                        "attributes": {
                            "property": "og:site_name",
                            "content": "Drupal GraphQL Demo"
                        }
                    },
                    {
                        "__typename": "MetaTagProperty",
                        "attributes": {
                            "property": "og:type",
                            "content": "website"
                        }
                    },
                    {
                        "__typename": "MetaTagProperty",
                        "attributes": {
                            "property": "og:url",
                            "content": "http:\/\/drupal-graphql-example.ddev.site\/blog"
                        }
                    },
                    {
                        "__typename": "MetaTagProperty",
                        "attributes": {
                            "property": "og:title",
                            "content": "Blog | Drupal GraphQL Demo"
                        }
                    },
                    {
                        "__typename": "MetaTagProperty",
                        "attributes": {
                            "property": "og:image",
                            "content": "http:\/\/drupal-graphql-example.ddev.site\/sites\/default\/files\/2024-04\/composabale-drop-logo.png"
                        }
                    },
                    {
                        "__typename": "MetaTagProperty",
                        "attributes": {
                            "property": "og:image:url",
                            "content": "http:\/\/drupal-graphql-example.ddev.site\/sites\/default\/files\/2024-04\/composabale-drop-logo.png"
                        }
                    },
                    {
                        "__typename": "MetaTagValue",
                        "attributes": {
                            "name": "twitter:card",
                            "content": "summary_large_image"
                        }
                    },
                    {
                        "__typename": "MetaTagValue",
                        "attributes": {
                            "name": "twitter:site",
                            "content": "@OctahedroidHQ"
                        }
                    },
                    {
                        "__typename": "MetaTagValue",
                        "attributes": {
                            "name": "twitter:title",
                            "content": "Blog"
                        }
                    },
                    {
                        "__typename": "MetaTagValue",
                        "attributes": {
                            "name": "twitter:creator:id",
                            "content": "@OctahedroidHQ"
                        }
                    },
                    {
                        "__typename": "MetaTagValue",
                        "attributes": {
                            "name": "twitter:creator",
                            "content": "@OctahedroidHQ"
                        }
                    },
                    {
                        "__typename": "MetaTagValue",
                        "attributes": {
                            "name": "twitter:image",
                            "content": "http:\/\/drupal-graphql-example.ddev.site\/sites\/default\/files\/2024-04\/composabale-drop-logo.png"
                        }
                    }
                ],
                "components": null
            }
        }
    },
    "$result->errors": [
        {
            "message": "Cannot return null for non-nullable field \"ParagraphViewReference.reference\".",
            "locations": [
                {
                    "line": 139,
                    "column": 3
                }
            ],
            "path": [
                "route",
                "entity",
                "components",
                0,
                "reference"
            ]
        }
    ],
    "$result->extensions": []
}
Previous errors:
For error #0: GraphQL\Error\InvariantViolation: Cannot return null for non-nullable field "ParagraphViewReference.reference". in GraphQL\Executor\ReferenceExecutor->completeValue() (line 748 of /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php)
#0 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\Executor\ReferenceExecutor->completeValue(Object(GraphQL\Type\Definition\NonNull), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, NULL)
#1 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\Executor\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\Type\Definition\NonNull), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, NULL)
#2 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\Executor\ReferenceExecutor->resolveField(Object(GraphQL\Type\Definition\ObjectType), Object(Drupal\paragraphs\Entity\Paragraph), Object(ArrayObject), Array)
#3 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1145): GraphQL\Executor\ReferenceExecutor->executeFields(Object(GraphQL\Type\Definition\ObjectType), Object(Drupal\paragraphs\Entity\Paragraph), Array, Object(ArrayObject))
#4 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1106): GraphQL\Executor\ReferenceExecutor->collectAndExecuteSubfields(Object(GraphQL\Type\Definition\ObjectType), Object(ArrayObject), Array, Object(Drupal\paragraphs\Entity\Paragraph))
#5 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(974): GraphQL\Executor\ReferenceExecutor->completeObjectValue(Object(GraphQL\Type\Definition\ObjectType), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(Drupal\paragraphs\Entity\Paragraph))
#6 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(789): GraphQL\Executor\ReferenceExecutor->completeAbstractValue(Object(GraphQL\Type\Definition\UnionType), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(Drupal\paragraphs\Entity\Paragraph))
#7 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(741): GraphQL\Executor\ReferenceExecutor->completeValue(Object(GraphQL\Type\Definition\UnionType), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(Drupal\paragraphs\Entity\Paragraph))
#8 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\Executor\ReferenceExecutor->completeValue(Object(GraphQL\Type\Definition\NonNull), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(Drupal\paragraphs\Entity\Paragraph))
#9 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(887): GraphQL\Executor\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\Type\Definition\NonNull), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Object(Drupal\paragraphs\Entity\Paragraph))
#10 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(761): GraphQL\Executor\ReferenceExecutor->completeListValue(Object(GraphQL\Type\Definition\ListOfType), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Array)
#11 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(651): GraphQL\Executor\ReferenceExecutor->completeValue(Object(GraphQL\Type\Definition\ListOfType), Object(ArrayObject), Object(GraphQL\Type\Definition\ResolveInfo), Array, Array)
#12 /var/www/html/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php(148): GraphQL\Executor\ReferenceExecutor->GraphQL\Executor\{closure}(Array)
#13 /var/www/html/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php(53): GraphQL\Executor\Promise\Adapter\SyncPromise->GraphQL\Executor\Promise\Adapter\{closure}()
#14 /var/www/html/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php(149): GraphQL\Executor\Promise\Adapter\SyncPromise::runQueue()
#15 /var/www/html/vendor/webonyx/graphql-php/src/Server/Helper.php(214): GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter->wait(Object(GraphQL\Executor\Promise\Promise))
#16 /var/www/html/web/modules/contrib/graphql/src/Entity/Server.php(200): GraphQL\Server\Helper->executeOperation(Object(GraphQL\Server\ServerConfig), Object(GraphQL\Server\OperationParams))
#17 /var/www/html/web/modules/contrib/graphql/src/Controller/RequestController.php(77): Drupal\graphql\Entity\Server->executeOperation(Object(GraphQL\Server\OperationParams))
#18 /var/www/html/web/modules/contrib/graphql/src/Controller/RequestController.php(63): Drupal\graphql\Controller\RequestController->handleSingle(Object(Drupal\graphql\Entity\Server), Object(GraphQL\Server\OperationParams))
#19 [internal function]: Drupal\graphql\Controller\RequestController->handleRequest(Object(Drupal\graphql\Entity\Server), Object(GraphQL\Server\OperationParams))
#20 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#21 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(627): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#22 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#23 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#24 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#25 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#26 /var/www/html/web/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#29 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#30 /var/www/html/web/core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#31 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#32 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#34 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#35 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#36 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#37 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#38 /var/www/html/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#39 {main}.
```

**Comment by drupalninja** [comment]
Easy fix, it looks like Drupal isn't setting the default view correctly on clean install:

<img width="945" alt="Screenshot 2024-05-05 at 1 16 42 PM" src="https://github.com/octahedroid/drupal-decoupled/assets/1112449/b113605f-70df-4c63-8e06-a33eeb29560e">

Once that is corrected (manually or otherwise) it works fine.

**Comment by jmolivas** [comment]
Thanks for reporting @drupalninja, seems like the single_content_sync is not exporting data correctly, need to double check if the "viewfield" module is supported and have it fixed if not ;)

**Comment by jmolivas** [comment]
To clarify a little bit more the answer, while this get resolved, this can be fixed it by editing the blog node page by visiting `/blog/edit` and updating the fields at the `components` tab 

![image](https://github.com/octahedroid/drupal-decoupled/assets/366275/42843f85-2465-4304-ab3f-1c8ab29e8906)
